language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"

install:
  - pip install -q cython
  - python setup.py install

# command to run tests, e.g. python setup.py test
script: py.test
