name: tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - os: windows-latest
            python-version: "2.7"
      fail-fast: false

    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: true
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
          python -m pip install --upgrade cython

      - name: "Rebuild CPP files using Cython"
        run: "./update_cpp.sh"

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"